name: CI

on: [push]

jobs: 
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2.0.0
    - run: cat $GITHUB_EVENT_PATH
    - uses: actions/setup-node@v1.1.0
    - uses: mooyoul/tslint-actions@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        pattern: '*.ts'
